### ISSUE TITLE
Current cursor text (selection)

### ISSUE THREAD

**Issue by CentaurWarchief** [rev087/fancy-new-file#23]
How about putting the current selected text on the file creation box?

There's a option for `Sublime-AdvancedNewFile` called `use_cursor_text` which does that when it holds **true**.

We already have that?
Thanks.

**Comment by Trudko** [comment]
Hi, nice nick were you warcraft player ? :)

Anyway I forked this repo because it seems abandoned so please take a look at [advanced-new-file](https://atom.io/packages/advanced-new-file). I might add this there when I have time. Only thing is that you can create multiple files at once with advanced-new-file so selected text would be appended on the end - the last file. That way I think it might work. Please [create issue to my repo](https://github.com/Trudko/advanced-new-file/issues/new) if you are still interested.

**Comment by CentaurWarchief** [comment]
@Trudko OFC, lol. Nein, not a Warcraft player.

Well, thnx.
:beers:
